ALTER TABLE employers
ALTER COLUMN yearly_revenue SET DATA TYPE FLOAT; -- PostegreSQL

ALTER TABLE employers
MODIFY COLUMN yearly_revenue FLOAT(5,2); -- MySQL

ALTER TABLE conversations
ALTER COLUMN date_send TYPE TIMESTAMP USING date_send::TIMESTAMP,
ALTER COLUMN date_send SET DEFAULT CURRENT_TIMESTAMP; -- PostgresSQL

ALTER TABLE conversations
MODIFY COLUMN date_send TIMESTAMP DEFAULT CURRENT_TIMESTAMP; -- MySQL

ALTER TABLE employers
ALTER COLUMN is_hiring SET DATA TYPE BOOLEAN,
ALTER COLUMN is_hiring SET DEFAULT FALSE; -- PostgreSQL

ALTER TABLE employers
MODIFY COLUMN is_hiring BOOLEAN DEFAULT FALSE; -- MySQL
